# Deployment configuration for the API Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway  # Name of the deployment
spec:
  replicas: 1  # Only one instance for demonstration purposes
  selector:
    matchLabels:
      app: api-gateway  # Ensures the pod matches this label
  template:
    metadata:
      labels:
        app: api-gateway  # Labels assigned to the pod
    spec:
      containers:
      - name: api-gateway
        image: containerization-demo-api-gateway:latest  # Use the locally built image
        ports:
        - containerPort: 3000  # The port the container listens on

---
# Service configuration for exposing the API Gateway
apiVersion: v1
kind: Service
metadata:
  name: api-gateway  # Name of the service
spec:
  selector:
    app: api-gateway  # Routes traffic to pods with this label
  ports:
    - protocol: TCP
      port: 3000  # Exposed service port inside the cluster
      targetPort: 3000  # Port on the container
      nodePort: 30000  # External access point for Minikube (optional)
  type: NodePort  # Use NodePort for local development in Minikube
